'use client';

import type { DashboardSummary } from '@/services/dashboard';
import { ArrowUpRight, BriefcaseBusiness, ChevronDown, CircleDollarSign, CreditCard, Sparkles, Target, TrendingUp } from 'lucide-react';

const inr = (value:number) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const lakhs = (value:number) => `₹${(value/100000).toFixed(2)}L`;

export function DashboardView({summary}:{summary:DashboardSummary}){
  const debtRatio=Math.round((summary.totalLiabilities/Math.max(summary.totalAssets,1))*100);
  const savingsRate=summary.monthlyNetSalary?38:0;
  const holdings=summary.holdings.slice(0,4);
  return <div className="space-y-4">
    <section className="grid gap-4 xl:grid-cols-[1.65fr_.8fr]">
      <article className="relative overflow-hidden rounded-2xl border border-white/10 bg-[#101d19] p-5 shadow-[0_20px_60px_rgba(0,0,0,.25)] sm:p-6">
        <div className="pointer-events-none absolute -right-16 -top-20 h-48 w-48 rounded-full bg-[#c9f56a]/[.05] blur-2xl"/>
        <div className="flex items-start justify-between"><div><p className="text-[10px] tracking-[.18em] text-[#6f8a80]">TOTAL NET WORTH</p><h2 className="mt-1 text-4xl font-black tracking-tight text-white sm:text-5xl">{lakhs(summary.netWorth)}</h2><p className="mt-2 text-[11px] font-semibold text-[#b8d764]"><ArrowUpRight className="mr-1 inline h-3.5 w-3.5"/>Live from confirmed financial records</p></div><button className="flex h-8 items-center gap-1 rounded-md border border-white/10 bg-white/[.03] px-2.5 text-[10px] font-bold text-[#7d978d] hover:text-white">1Y <ChevronDown size={12}/></button></div>
        <div className="mt-5 h-44 rounded-xl border border-white/5 bg-[#0b1512] p-3"><div className="h-full rounded-lg border-b border-white/10 bg-[linear-gradient(165deg,transparent_58%,rgba(201,245,106,.08)_58%)]"/></div>
        <div className="mt-4 grid grid-cols-3 border-t border-white/10 pt-4 text-[11px]"><div><p className="text-[#5f786f]">Assets</p><b className="mt-1 block text-white">{lakhs(summary.totalAssets)}</b></div><div><p className="text-[#5f786f]">Liabilities</p><b className="mt-1 block text-white">{lakhs(summary.totalLiabilities)}</b></div><div><p className="text-[#5f786f]">Monthly income</p><b className="mt-1 block text-[#c9f56a]">{lakhs(summary.monthlyNetSalary)}</b></div></div>
      </article>
      <article className="relative overflow-hidden rounded-2xl border border-[#263a31] bg-[#c9f56a] p-6 text-[#0d241a] shadow-[0_20px_60px_rgba(201,245,106,.08)]"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-white/20 blur-2xl"/><p className="text-[10px] tracking-[.18em] text-[#3f5b49]">FINANCIAL HEALTH</p><h2 className="mt-1 text-5xl font-black tracking-tight">84<span className="text-sm font-bold text-[#506a57]">/100</span></h2><div className="mt-6 h-2 overflow-hidden rounded-full bg-[#abc85a]"><div className="h-full w-[84%] rounded-full bg-[#16362a]"/></div><p className="mt-5 max-w-[260px] text-xs font-medium leading-5 text-[#38513f]">Strong trajectory. Your investment base and income give you a solid platform for the next goal.</p><button className="mt-4 rounded-lg bg-[#16362a] px-3 py-2 text-[11px] font-bold text-[#d9f996]">View scorecard →</button></article>
    </section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<TrendingUp size={17}/>} title="Investments" value={lakhs(summary.totalInvestments)} detail="Across live holdings"/><Metric icon={<CircleDollarSign size={17}/>} title="Monthly surplus" value={inr(Math.max(summary.monthlyNetSalary*savingsRate/100,0))} detail={`${savingsRate}% savings rate`}/><Metric icon={<Target size={17}/>} title="Goal funding" value="68%" detail="Home & FI plan on track"/><Metric icon={<CreditCard size={17}/>} title="Debt-to-assets" value={`${debtRatio}%`} detail={debtRatio<30?'Healthy balance sheet':'Review debt plan'}/></section>

    <section className="grid gap-4 xl:grid-cols-2">
      <article className="rounded-2xl border border-white/10 bg-[#101d19] p-5"><div className="flex items-start justify-between"><div><h3 className="text-sm font-extrabold text-white">Portfolio intelligence</h3><p className="mt-1 text-[11px] text-[#678278]">Live holdings from your data workspace</p></div><span className="rounded bg-[#c9f56a]/10 px-2 py-1 font-mono text-[9px] text-[#b8d764]">{summary.holdings.length} HOLDINGS</span></div><div className="mt-5 space-y-3">{holdings.length?holdings.map((holding)=><div key={holding.id} className="flex items-center gap-3 rounded-lg border border-white/5 bg-white/[.02] px-3 py-2.5"><span className="h-2 w-2 rounded-sm bg-[#c9f56a]"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold text-white">{holding.assetName}</p><p className="text-[10px] text-[#607970]">{holding.assetType||'Investment'}{holding.platform?` · ${holding.platform}`:''}</p></div><b className="text-xs text-white">{lakhs(holding.currentValue)}</b></div>):<p className="rounded-lg bg-white/[.03] p-4 text-xs text-[#6f8a80]">Add investment holdings in Supabase to populate portfolio intelligence.</p>}</div></article>
      <article className="rounded-2xl border border-[#30453b] bg-[#0f2a21] p-5 text-white shadow-[0_18px_50px_rgba(0,0,0,.22)]"><div className="flex items-center gap-2"><span className="grid h-8 w-8 place-items-center rounded-lg bg-[#c9f56a] text-[#0f2a21]"><Sparkles size={16}/></span><p className="font-mono text-[10px] tracking-[.16em] text-[#b4c9be]">ARTHA INTELLIGENCE</p></div><h3 className="mt-4 max-w-sm text-xl font-black leading-7">You could reach financial independence <span className="text-[#c9f56a]">earlier.</span></h3><p className="mt-3 max-w-md text-xs leading-5 text-[#9ab4a8]">Redirecting part of your monthly surplus toward long-term investments could improve your projected timeline.</p><button className="mt-5 rounded-lg bg-[#c9f56a] px-3 py-2 text-[11px] font-extrabold text-[#10251c]">Explore scenario analysis →</button></article>
    </section>

    <section className="grid gap-4 xl:grid-cols-[1.4fr_.8fr]"><article className="rounded-2xl border border-white/10 bg-[#101d19] p-5"><div className="flex justify-between"><div><h3 className="text-sm font-extrabold text-white">Debt & liquidity watch</h3><p className="mt-1 text-[11px] text-[#678278]">Priority action based on current liabilities</p></div><BriefcaseBusiness size={18} className="text-[#c9f56a]"/></div><div className="mt-5 rounded-xl border border-[#2a3e35] bg-[#0b1512] p-4"><p className="text-xs font-bold text-white">Keep high-cost debt ahead of discretionary investing.</p><p className="mt-1 text-[11px] leading-5 text-[#667f75]">Current liability balance is {inr(summary.totalLiabilities)}. Add interest rates and EMIs to unlock the prepayment optimizer.</p></div></article><article className="rounded-2xl border border-white/10 bg-[#101d19] p-5"><p className="text-[10px] tracking-[.18em] text-[#637d73]">DATA FOUNDATION</p><h3 className="mt-1 text-sm font-extrabold text-white">Ready for the next layer</h3><div className="mt-4 space-y-2 text-[11px]"><Status label="Salary and net worth snapshot" done/><Status label="Investment holdings" done={summary.holdings.length>0}/><Status label="Document ingestion & review"/><Status label="Scenario simulator"/></div></article></section>
  </div>
}

function Metric({icon,title,value,detail}:{icon:React.ReactNode;title:string;value:string;detail:string}){return <article className="flex items-center gap-3 rounded-2xl border border-white/10 bg-[#101d19] p-4 shadow-[0_10px_30px_rgba(0,0,0,.16)]"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#c9f56a]/10 text-[#c9f56a]">{icon}</span><div><p className="text-[10px] text-[#657f75]">{title}</p><p className="mt-0.5 text-base font-extrabold tracking-tight text-white">{value}</p><p className="text-[9px] text-[#5a7168]">{detail}</p></div></article>}
function Status({label,done=false}:{label:string;done?:boolean}){return <p className="flex items-center justify-between border-b border-white/10 pb-2 last:border-0"><span className="text-[#819b90]">{label}</span><span className={`rounded px-1.5 py-0.5 text-[9px] font-bold ${done?'bg-[#c9f56a]/10 text-[#c9f56a]':'bg-white/[.04] text-[#647b72]'}`}>{done?'READY':'NEXT'}</span></p>}
