'use client';

import type { DashboardSummary } from '@/services/dashboard';
import { ArrowUpRight, BriefcaseBusiness, ChevronDown, CircleDollarSign, CreditCard, Sparkles, Target, TrendingUp } from 'lucide-react';

const inr = (value:number) => new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
const lakhs = (value:number) => `₹${(value/100000).toFixed(2)}L`;

export function DashboardView({summary}:{summary:DashboardSummary}){
  const debtRatio=Math.round((summary.totalLiabilities/Math.max(summary.totalAssets,1))*100);
  const savingsRate=summary.monthlyNetSalary?38:0;
  const holdings=summary.holdings.slice(0,4);
  return <div className="space-y-4">
    <section className="grid gap-4 xl:grid-cols-[1.65fr_.8fr]">
      <article className="rounded-2xl border border-[#dce6df] bg-white p-5 shadow-sm sm:p-6">
        <div className="flex items-start justify-between"><div><p className="text-[10px] tracking-[.16em] text-slate-500">TOTAL NET WORTH</p><h2 className="mt-1 text-4xl font-extrabold tracking-tight sm:text-5xl">{lakhs(summary.netWorth)}</h2><p className="mt-2 text-[11px] font-semibold text-[#087059]"><ArrowUpRight className="mr-1 inline h-3.5 w-3.5"/>Live from confirmed financial records</p></div><button className="flex h-8 items-center gap-1 rounded-md border border-[#dce6df] px-2.5 text-[10px] font-bold text-slate-600">1Y <ChevronDown size={12}/></button></div>
        <div className="mt-5 h-44 rounded-xl bg-gradient-to-t from-[#eef5ef] to-transparent p-3"><div className="h-full rounded-lg border-b border-[#dce6df] bg-[linear-gradient(165deg,transparent_58%,rgba(8,112,89,.10)_58%)]"/></div>
        <div className="mt-4 grid grid-cols-3 border-t border-[#e8eeea] pt-4 text-[11px]"><div><p className="text-slate-500">Assets</p><b className="mt-1 block">{lakhs(summary.totalAssets)}</b></div><div><p className="text-slate-500">Liabilities</p><b className="mt-1 block">{lakhs(summary.totalLiabilities)}</b></div><div><p className="text-slate-500">Monthly income</p><b className="mt-1 block text-[#087059]">{lakhs(summary.monthlyNetSalary)}</b></div></div>
      </article>
      <article className="rounded-2xl bg-[#e6f0e4] p-6"><p className="text-[10px] tracking-[.16em] text-slate-500">FINANCIAL HEALTH</p><h2 className="mt-1 text-5xl font-extrabold tracking-tight">84<span className="text-sm font-medium text-slate-500">/100</span></h2><p className="mt-6 max-w-[260px] text-xs leading-5 text-[#51695e]">Strong trajectory. Your investment base and income give you a solid platform for the next goal.</p><button className="mt-4 text-xs font-bold text-[#087059]">View scorecard →</button></article>
    </section>

    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={<TrendingUp size={17}/>} title="Investments" value={lakhs(summary.totalInvestments)} detail="Across live holdings"/><Metric icon={<CircleDollarSign size={17}/>} title="Monthly surplus" value={inr(Math.max(summary.monthlyNetSalary*savingsRate/100,0))} detail={`${savingsRate}% savings rate`}/><Metric icon={<Target size={17}/>} title="Goal funding" value="68%" detail="Home & FI plan on track"/><Metric icon={<CreditCard size={17}/>} title="Debt-to-assets" value={`${debtRatio}%`} detail={debtRatio<30?'Healthy balance sheet':'Review debt plan'}/></section>

    <section className="grid gap-4 xl:grid-cols-2">
      <article className="rounded-2xl border border-[#dce6df] bg-white p-5"><div className="flex items-start justify-between"><div><h3 className="text-sm font-extrabold">Portfolio intelligence</h3><p className="mt-1 text-[11px] text-slate-500">Live holdings from your data workspace</p></div><span className="rounded bg-[#e8f1d9] px-2 py-1 font-mono text-[9px] text-[#587517]">{summary.holdings.length} HOLDINGS</span></div><div className="mt-5 space-y-3">{holdings.length?holdings.map((holding)=><div key={holding.id} className="flex items-center gap-3"><span className="h-2 w-2 rounded-sm bg-[#087059]"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{holding.assetName}</p><p className="text-[10px] text-slate-500">{holding.assetType||'Investment'}{holding.platform?` · ${holding.platform}`:''}</p></div><b className="text-xs">{lakhs(holding.currentValue)}</b></div>):<p className="rounded-lg bg-[#f4f7f4] p-4 text-xs text-slate-500">Add investment holdings in Supabase to populate portfolio intelligence.</p>}</div></article>
      <article className="rounded-2xl bg-[#183a2e] p-5 text-white"><Sparkles className="h-5 w-5 text-[#caf060]"/><p className="mt-3 font-mono text-[10px] tracking-[.12em] text-[#afc7b8]">ARTHA INTELLIGENCE</p><h3 className="mt-2 max-w-sm text-xl font-extrabold leading-7">You could reach financial independence <span className="text-[#caf060]">earlier.</span></h3><p className="mt-3 max-w-md text-xs leading-5 text-[#b8cdc0]">Redirecting part of your monthly surplus toward long-term investments could improve your projected timeline.</p><button className="mt-5 rounded-md bg-[#caf060] px-3 py-2 text-[11px] font-bold text-[#183a2e]">Explore scenario analysis →</button></article>
    </section>

    <section className="grid gap-4 xl:grid-cols-[1.4fr_.8fr]"><article className="rounded-2xl border border-[#dce6df] bg-white p-5"><div className="flex justify-between"><div><h3 className="text-sm font-extrabold">Debt & liquidity watch</h3><p className="mt-1 text-[11px] text-slate-500">Priority action based on current liabilities</p></div><BriefcaseBusiness size={18} className="text-[#087059]"/></div><div className="mt-5 rounded-xl bg-[#f1f6ef] p-4"><p className="text-xs font-bold">Keep high-cost debt ahead of discretionary investing.</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Current liability balance is {inr(summary.totalLiabilities)}. Add interest rates and EMIs to unlock the prepayment optimizer.</p></div></article><article className="rounded-2xl border border-[#dce6df] bg-white p-5"><p className="text-[10px] tracking-[.16em] text-slate-500">DATA FOUNDATION</p><h3 className="mt-1 text-sm font-extrabold">Ready for the next layer</h3><div className="mt-4 space-y-2 text-[11px]"><Status label="Salary and net worth snapshot" done/><Status label="Investment holdings" done={summary.holdings.length>0}/><Status label="Document ingestion & review"/><Status label="Scenario simulator"/></div></article></section>
  </div>
}

function Metric({icon,title,value,detail}:{icon:React.ReactNode;title:string;value:string;detail:string}){return <article className="flex items-center gap-3 rounded-xl border border-[#dce6df] bg-white p-4"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#eef3ef] text-[#087059]">{icon}</span><div><p className="text-[10px] text-slate-500">{title}</p><p className="mt-0.5 text-base font-extrabold tracking-tight">{value}</p><p className="text-[9px] text-slate-500">{detail}</p></div></article>}
function Status({label,done=false}:{label:string;done?:boolean}){return <p className="flex items-center justify-between border-b border-[#edf1ee] pb-2 last:border-0"><span className="text-slate-600">{label}</span><span className={`rounded px-1.5 py-0.5 text-[9px] font-bold ${done?'bg-[#e9f4e5] text-[#3b784b]':'bg-[#f1f3f1] text-slate-500'}`}>{done?'READY':'NEXT'}</span></p>}
