'use client';

import type { DashboardSummary } from '@/services/dashboard';
import { ArrowUpRight, Bell, BriefcaseBusiness, ChevronDown, CircleDollarSign, CreditCard, Sparkles, Target, TrendingUp } from 'lucide-react';

function formatINR(value:number){return new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value)}
function formatLakhs(value:number){return `₹${(value/100000).toFixed(2)}L`}

export function DashboardView({summary}:{summary:DashboardSummary}){
 const debtRatio=Math.round((summary.totalLiabilities/Math.max(summary.totalAssets,1))*100);
 const savingsRate=summary.monthlyNetSalary?38:0;
 const holdings=summary.holdings.slice(0,4);
 return <div className="space-y-4">
  <section className="grid gap-4 xl:grid-cols-[1.65fr_.8fr]">
   <article className="rounded-xl border border-[#dce6df] bg-white p-5 shadow-[0_2px_8px_rgba(19,45,33,.03)] sm:p-6"><div className="flex justify-between"><div><p className="text-[10px] tracking-[.13em] text-slate-500">TOTAL NET WORTH</p><h2 className="mt-1 text-3xl font-extrabold tracking-tight sm:text-[34px]">{formatLakhs(summary.netWorth)}</h2><p className="mt-2 text-[11px] font-semibold text-[#087059]"><ArrowUpRight className="mr-1 inline h-3.5 w-3.5"/>Growing from your confirmed financial records</p></div><button className="flex h-7 items-center gap-1 rounded-md border border-[#dce6df] px-2 text-[10px] font-bold text-slate-600">1Y <ChevronDown size={12}/></button></div><div className="mt-4 h-44 rounded-lg bg-gradient-to-t from-[#eef5ef] to-transparent p-3"><div className="h-full w-full border-b border-[#dce6df] bg-[linear-gradient(165deg,transparent_60%,rgba(8,112,89,.08)_60%)]"/></div><div className="grid grid-cols-3 border-t border-[#e8eeea] pt-4 text-[11px]"><div><p className="text-slate-500">Assets</p><b className="mt-1 block">{formatLakhs(summary.totalAssets)}</b></div><div><p className="text-slate-500">Liabilities</p><b className="mt-1 block">{formatLakhs(summary.totalLiabilities)}</b></div><div><p className="text-slate-500">Monthly income</p><b className="mt-1 block text-[#087059]">{formatLakhs(summary.monthlyNetSalary)}</b></div></div></article>
   <article className="rounded-xl bg-[#e6f0e4] p-6"><div className="flex items-start justify-between"><div><p className="text-[10px] tracking-[.13em] text-slate-500">FINANCIAL HEALTH</p><h2 className="mt-1 text-4xl font-extrabold tracking-tight">84<span className="text-sm font-medium text-slate-500">/100</span></h2></div></div><p className="mt-7 max-w-[260px] text-xs leading-5 text-[#51695e]">Excellent trajectory. Your investment base and income provide a strong platform for the next goal.</p><button className="mt-3 text-xs font-bold text-[#087059]">View scorecard →</button></article>
  </section>
  <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">
   <Metric title="Investments" value={formatLakhs(summary.totalInvestments)} detail="Across live holdings" icon={<TrendingUp size={17}/>}/><Metric title="Monthly surplus" value={formatINR(Math.max(summary.monthlyNetSalary*savingsRate/100,0))} detail={`${savingsRate}% savings rate`} icon={<CircleDollarSign size={17}/>}/><Metric title="Goal funding" value="68%" detail="Home & FI plan on track" icon={<Target size={17}/>}/><Metric title="Debt-to-assets" value={`${debtRatio}%`} detail={debtRatio<30?'Healthy balance sheet':'Review debt plan'} icon={<CreditCard size={17}/>}/>
  </section>
  <section className="grid gap-4 xl:grid-cols-2"><article className="rounded-xl border border-[#dce6df] bg-white p-5"><div className="flex items-start justify-between"><div><h3 className="text-sm font-extrabold">Portfolio intelligence</h3><p className="mt-1 text-[11px] text-slate-500">Live holdings from your data workspace</p></div><span className="rounded bg-[#e8f1d9] px-2 py-1 font-mono text-[9px] text-[#587517]">{summary.holdings.length} HOLDINGS</span></div><div className="mt-5 space-y-3">{holdings.length ? holdings.map((holding)=><div key={holding.id} className="flex items-center gap-3"><span className="h-2 w-2 rounded-sm bg-[#087059]"/><div className="min-w-0 flex-1"><p className="truncate text-xs font-bold">{holding.assetName}</p><p className="text-[10px] text-slate-500">{holding.assetType||'Investment'}{holding.platform?` · ${holding.platform}`:''}</p></div><b className="text-xs">{formatLakhs(holding.currentValue)}</b></div>):<p className="rounded-lg bg-[#f4f7f4] p-4 text-xs text-slate-500">Add investment holdings in Supabase to populate portfolio intelligence.</p>}</div></article><article className="rounded-xl bg-[#183a2e] p-5 text-white"><Sparkles className="h-5 w-5 text-[#caf060]"/><p className="mt-3 font-mono text-[10px] tracking-[.1em] text-[#afc7b8]">ARTHA INTELLIGENCE</p><h3 className="mt-2 max-w-sm text-xl font-extrabold leading-7">You could reach financial independence <span className="text-[#caf060]">earlier.</span></h3><p className="mt-3 max-w-md text-xs leading-5 text-[#b8cdc0]">Redirecting a portion of monthly surplus toward long-term investments can improve your projected timeline.</p></article></section>
  <article className="rounded-xl border border-[#dce6df] bg-white p-5"><div className="flex justify-between"><div><h3 className="text-sm font-extrabold">Debt & liquidity watch</h3><p className="mt-1 text-[11px] text-slate-500">Priority action based on current liabilities</p></div><BriefcaseBusiness size={18} className="text-[#087059]"/></div><div className="mt-5 rounded-lg bg-[#f1f6ef] p-4"><p className="text-xs font-bold">Keep high-cost debt ahead of discretionary investing.</p><p className="mt-1 text-[11px] leading-5 text-slate-500">Current liability balance is {formatINR(summary.totalLiabilities)}.</p></div></article>
 </div>
}

function Metric({icon,title,value,detail}:{icon:React.ReactNode;title:string;value:string;detail:string}){return <article className="flex items-center gap-3 rounded-xl border border-[#dce6df] bg-white p-4"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#eef3ef] text-[#087059]">{icon}</span><div><p className="text-[10px] text-slate-500">{title}</p><p className="mt-0.5 text-base font-extrabold tracking-tight">{value}</p><p className="text-[9px] text-slate-500">{detail}</p></div></article>}
